[package]
name = "queue-pow"
version = "1.0.0"
edition = "2021"

[dependencies]
crypto = { version = "0.3.0", features = ["digest"] }
base64 = "0.13.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sha2 = "0.10.2"
